### ISSUE TITLE
Week3 - Explain About the experiment and code snippet seperatly

### ISSUE THREAD

**Issue by appuCoding** [meera1/v4.0#1]
Explanation should be at least a paragraph (3-4 sentences)

**Comment by meera1** [comment]
Sure will do it. Thanks.
Sent using CloudMagic
On Wed, Feb 11, 2015 at 5:11 pm, sneha Vankireddy notifications@github.com wrote:Explanation should be at least a paragraph (3-4 sentences)

**Comment by meera1** [comment]
Done
