### ISSUE TITLE
Write Blog Every week

### ISSUE THREAD

**Issue by appuCoding** [meera1/v4.0#2]
No blog for week1 ,2 ,3

**Comment by meera1** [comment]
Blog as in? Documentation?
Sent using CloudMagic
On Wed, Feb 11, 2015 at 5:14 pm, sneha Vankireddy notifications@github.com wrote:No blog for week1 ,2 ,3

**Comment by appuCoding** [comment]
Come and meet me in TA hours.

**Comment by meera1** [comment]
Done
